### ISSUE TITLE
Plugin doesn't detect file as mdx

### ISSUE THREAD

**Issue by leonied7** [valentinnodan/mdx-intellij-plugin#10]
Hello!

Plugin doesn't detect mdx if create file with name `attached-vacancy-list.stories.mdx` 
<img width="248" alt="Снимок экрана 2021-02-01 в 18 04 56" src="https://user-images.githubusercontent.com/25240326/106450623-007ec480-64b8-11eb-9c0c-816aeabb1e88.png">

Highlights don't work too
<img width="705" alt="Снимок экрана 2021-02-01 в 18 05 38" src="https://user-images.githubusercontent.com/25240326/106450846-518eb880-64b8-11eb-97ab-52abbe56be1b.png">

**Comment by prigara** [comment]
Please check that the `*.mdx` file pattern is associated with the MDX file type in the IDE Preferences | Editor | File types.
If the problem happens only with this specific file, please check that this file name is not assigned to the Text file type.

**Comment by leonied7** [comment]
@prigara, you right! I found it
<img width="654" alt="Снимок экрана 2021-02-01 в 22 11 18" src="https://user-images.githubusercontent.com/25240326/106477144-6b40f780-64da-11eb-90f9-660263fb5c63.png">
