### ISSUE TITLE
I can't type changes in my file

### ISSUE THREAD

**Issue by afharo** [valentinnodan/mdx-intellij-plugin#11]
When I enabled the plugin in the latest version of WebStorm, it worked as expected.

Then I restarted it and the file stayed in the `loading` spinner forever.
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/5469006/106601804-fc07e980-6553-11eb-9b95-c9c7838c2f9b.png">

I disabled the plugin, the file loads. I enable it, highlighting works but I can't type (for some reason I can delete to the right but not to the left) 🤷 

Details about my installation:

```
WebStorm 2020.3.2
Build #WS-203.7148.54, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 8083M
Cores: 16
Registry: typescript.service.node.arguments=--max_old_space_size=9216
Non-Bundled Plugins: com.vecheslav.darculaDarkerTheme, org.toml.lang, ru.adelf.idea.dotenv, org.asciidoctor.intellij.asciidoc
```

MDX version installed: 1.1

**Comment by prigara** [comment]
Could you please share the IDE logs (menu Help - Collect Logs)? Thanks!

**Comment by afharo** [comment]
Sure thing! Here they are! Thank you!

[webstorm-logs-20210202-143442.zip](https://github.com/valentinnodan/mdx-intellij-plugin/files/5911469/webstorm-logs-20210202-143442.zip)

**Comment by prigara** [comment]
Thanks! There's a bunch of exceptions related to Markdown. Any chance you can share your MDX file?

**Comment by afharo** [comment]
I think I can share this file (I'm getting errors in it as well)

[docsSyntax.mdx.zip](https://github.com/valentinnodan/mdx-intellij-plugin/files/5912950/docsSyntax.mdx.zip)

Thanks again!

**Comment by anstarovoyt** [comment]
Simplified example:

```
### Internal links

```html
<DocLink id="docsSyntax" />
<DocLink id="docsSyntax" text="Different link text"/>
<DocLink id="docsSyntax" tooltip />
<DocLink id="docsSyntax" section="unordered-lists" text="Linking to a specific section" />
```

* <DocLink id="docsSyntax" />
* <DocLink id="docsSyntax" text="Different link text"/>
* <DocLink id="docsSyntax" tooltip />
* <DocLink id="docsSyntax" section="unordered-lists" text="Linking to a specific section" />

If you include a `section` qualifier, you must use the resolved anchor ID
(e.g. `"unordered-lists"`); do not use the section title (e.g. `"unordered lists"`).
```

**Comment by anstarovoyt** [comment]
the problem here is that the tag AST element was extended to the next line, while the parent element (list item) is a one-line only element.
