### ISSUE TITLE
how to install the plugin ?

### ISSUE THREAD

**Issue by find456789** [valentinnodan/mdx-intellij-plugin#22]
hi, there

in the plugin store, i can't find this plugin 

https://plugins.jetbrains.com/search?search=mdx-intellij-plugin

how to install the plugin to my webstorm 

thank you very much !

**Comment by vladsholokhov** [comment]
Hi! Here is the link - https://plugins.jetbrains.com/plugin/14944-mdx

**Comment by find456789** [comment]
@vladsholokhov  

hi ,thank you

https://plugins.jetbrains.com/plugin/14944-mdx    the plugin owner is JetBrains s.r.o., it have no support mdx v2

i hope it support mdx v2

do you have any idea?

**Comment by vladsholokhov** [comment]
Unfortunately, it’s not quite clear what the problem is. Can you please describe it in more detail? What kind of issue you have with MDX2 and the plugin?

**Comment by find456789** [comment]
thank you， @vladsholokhov 

is this support mdx2 ?   https://mdxjs.com/blog/v2/

**Comment by vladsholokhov** [comment]
There is no support for JS expressions yet - https://github.com/valentinnodan/mdx-intellij-plugin/issues/23.
The rest should work fine.

**Comment by find456789** [comment]
@vladsholokhov    thank you very much
