### ISSUE TITLE
Syntax highlight error for comments

### ISSUE THREAD

**Issue by archangel-irk** [valentinnodan/mdx-intellij-plugin#7]
Hello guys, thank you for this amazing plugin!
I found a problem with comments and highlights for them. See a screenshot below.

![image](https://user-images.githubusercontent.com/1079509/94469923-8e2b6a00-01cf-11eb-9998-d5f560315eb1.png)

Source:
```
<!--<Meta
  title="Button"
  component={Button}
  argTypes={{
    disabled: {
      name: 'disabled',
      description: 'Disabled state of button',
      defaultValue: false,
      type: 'boolean',
      control: 'boolean',
    },
  }}
/>

<!-- https://github.com/storybookjs/storybook/issues/11542 -->
<!-- https://github.com/storybookjs/storybook/issues/11813 -->

<!-- export const Template = (args) => <Button {...args} style={{ marginRight: 'var(--fr-size-xs)' }} />; -->

<!-- How to write styles
<style>{`
  .subheading {
    --mediumdark: '#999999';
    font-weight: 900;
    font-size: 13px;
  }
`}</style>
-->
```

I found that this syntax `<!--I'm a comment-->` will be removed in favor of `{/*I'm a comment*/}`, but I think it's good to support both.
https://github.com/mdx-js/mdx/pull/1039

**Comment by anstarovoyt** [comment]
fixed the MDX part (so no any errors now). Unfortunately "proper" comments-like highlighting should be implemented on the markdown plugin side.

The fix is available only for the upcoming 2020.3. If it is a big issue for you, please let me know. I will try to backport the fix to 2020.2.
